embedding_size: 64
feat_embed_dim: 64


n_layers: 2
mm_image_weight: [0.5]
aggr_mode: ['add']
knn_k: [10]
k: [50]
n_mm_layers: [1, 2]
u_layers: [1, 2]
learning_rate: [0.0001]
reg_weight: [0.0001]
hyper_parameters: ["mm_image_weight","k", "u_layers", "n_mm_layers", "knn_k", "aggr_mode", "reg_weight", "learning_rate"]